DROP SEQUENCE global_seq IF EXISTS;
DROP TABLE person IF EXISTS;
DROP TABLE record_book IF EXISTS;
DROP TABLE student IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE person
(
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  passport_seria INTEGER NOT NULL,
  passport_number INTEGER NOT NULL,
  last_name VARCHAR(75),
  first_name VARCHAR(75),
  middle_name VARCHAR(75)
);
CREATE UNIQUE INDEX person_unique_idx ON person (passport_seria, passport_number);

CREATE TABLE record_book
(
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  code INTEGER NOT NULL
);
CREATE UNIQUE INDEX record_book_unique_idx ON record_book (code);

CREATE TABLE student
(
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  record_book INTEGER,
  person INTEGER NOT NULL,
  group_name VARCHAR(150),
  FOREIGN KEY (record_book) REFERENCES record_book (id) ON DELETE CASCADE,
  FOREIGN KEY (person) REFERENCES person (id) ON DELETE CASCADE
);
